name: Build I18N
run-name: 小月珰正在打包汉化词典，吱嘎

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      chinese_version:
        description: "汉化版本"

permissions:
  contents: write

env:
  GIT_REPO: ${{secrets.GIT_REPO}}
  PARATRANZ_TOKEN: ${{secrets.PARATRANZ_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CHINESE_VERSION: alpha4.1.0
  SOURCE_TYPE: common

jobs:
  build-i18n-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date + '%Y%m%d')"

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          submodules: true

      - name: Fetch game source code
        working-directory: ${{ github.workspace }}/vrelnir_localization
        run: git submodule update --init --recursive

      - name: Python installation
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10.11'
          cache: 'pip'

      - name: Python libs installation
        working-directory: ${{ github.workspace }}/vrelnir_localization
        run: pip install -r requirements.txt

      - name: Generating i18n.json (in data/json/i18n.json)
        working-directory: ${{ github.workspace }}/vrelnir_localization
        run: python ./build.py

      - name: Get game version
        id: game_version
        run: |
          version=`cat ${{ github.workspace }}/vrelnir_localization/degrees-of-lewdity-master/version`
          echo "::set-output name=version::version"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: ModLoader
        uses: actions/checkout@v4
        with:
          repository: Lyoko-Jeremie/sugarcube-2-ModLoader
          path: ModLoader
          ref: master
          submodules: recursive

      - name: Build ModLoader
        working-directory: ${{ github.workspace }}/ModLoader
        run: |
          yarn install
          yarn run ts:BeforeSC2
          yarn run webpack:BeforeSC2
          yarn run ts:ForSC2
          yarn run webpack:insertTools

      - name: Build i18n
        working-directory: ${{ github.workspace }}/ModLoader/mod/i18n
        run: |
          yarn install
          yarn run ts:build

      - name: Copy img (Win)
        if: runner.os == 'Windows'
        run: copy -Path "${{ github.workspace }}/vrelnir_localization/data/json/i18n.json" -Destination "${{ github.workspace }}/ModLoader/mod/i18n/i18n.json"

      - name: Copy img (Linux)
        if: runner.os == 'Linux'
        run: cp "${{ github.workspace }}/vrelnir_localization/data/json/i18n.json" "${{ github.workspace }}/ModLoader/mod/i18n/i18n.json"

      - name: change mod version in boot.json on scheduled task
        if: ${{ github.event_name }} == 'schedule'
        working-directory: ${{ github.workspace }}
        run: node "${{ github.workspace }}/change_mod_version.js" "${{ github.workspace }}/ModLoader/mod/i18n/boot.json" "${{ env.CHINESE_VERSION }}" "${{ steps.game_version.outputs.version }}"

      - name: change mod version in boot.json on manual task
        if: ${{ github.event_name }} == 'workflow_dispatch'
        working-directory: ${{ github.workspace }}
        run: node "${{ github.workspace }}/change_mod_version.js" "${{ github.workspace }}/ModLoader/mod/i18n/boot.json" "${{ github.event.inputs.chinese_version }}" "${{ steps.game_version.outputs.version }}"

      - name: Build i18n Mod
        working-directory: ${{ github.workspace }}/ModLoader/mod/i18n
        run: node "${{ github.workspace }}/ModLoader/dist-insertTools/packModZip.js" "boot.json"

      - name: Upload i18n Mod
        uses: actions/upload-artifact@v3
        with:
          name: I18nMod-${{ github.sha }}
          path: ${{ github.workspace }}/ModLoader/mod/i18n/ModI18N.mod.zip

      - name: Release Auto-build Nightly
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name }} == 'schedule'
        with:
          files: ${{ github.workspace }}/ModLoader/mod/i18n/ModI18N.mod.zip
          name: Auto Release nightly v${{ steps.game_version.outputs.version }}-chs-${{ env.CHINESE_VERSION }}-auto-${{ steps.date.outputs.date }}
          tag_name: ${{ steps.game_version.outputs.version }}-chs-${{ env.CHINESE_VERSION }}-auto-${{ steps.date.outputs.date }}
          body: Scheduled task on ${{ steps.date.outputs.date }}
          prerelease: true

      - name: Release Manually build
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name }} == 'workflow_dispatch'
        with:
          files: ${{ github.workspace }}/ModLoader/mod/i18n/ModI18N.mod.zip
          name: Release v${{ steps.game_version.outputs.version }}-chs-${{ github.event.inputs.chinese_version }}
          tag_name: ${{ steps.game_version.outputs.version }}-chs-${{ github.event.inputs.chinese_version }}
          body: release v${{ steps.game_version.outputs.version }}-chs-${{ github.event.inputs.chinese_version }}
